spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5432}/${DB_NAME:franchise}
    username: ${DB_USERNAME:franchise}
    password: ${DB_PASSWORD}
  data:
    r2dbc:
      repositories:
        enabled: true